# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default
 # vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: "inline"
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello knoldus here"

- task: PowerShell@2
  displayName: "powershell from script"
  inputs:
    filePath: 'demo.ps1'